inherit:
    - ../standard.yaml
    - ../wandb.yaml

model:
    n_layer: 2
    n_embd: 64
    seq_op: base_conv
    conv_type: short
    n_head: 2

    use_mlps: True
    mlp_upfactor: 4
    mlp_activ: relu

training:
    optimizer: adam
    train_steps: 1000001
    batch_size: 1024
    learning_rate: 0.001
    weight_decay: 0

    scheduler: step_threshold
    scheduler_steprate: 10000
    scheduler_gamma: 0.9
    
    keep_every_steps: 10000

autoname: False

wandb:
    log_every_steps: 1000
