inherit:
    - default_recipe.yaml

model:
    n_layer: 6
    n_dims: 5
    in_dims: 6
    out_dims: 5
    n_positions: 21

training:
    learning_rate: 0.01

    data: least_squares
    data_kwargs: {"seed": 1}
    task: multistep_gd
    task_kwargs: {"num_iters": 4, "step_size": 0.5}
    curriculum:
        points:
            start: 20
            end: 20
            inc: 2
            interval: 3000
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 3000
    keep_every_steps: 10000

autoname: False
out_dir: models/task=multistep_step=4

wandb:
    name: "task=multistep_step=4"
